[tox]
envlist = translation

[testenv:translation]
allowlist_externals =
    sh
    rm
    msgmerge
basepython = python3.11
changedir = {toxinidir}/video_xblock
deps =
    django<5.0
    edx-i18n-tools
commands =
    # Extract source translation string using the i18n tool
    i18n_tool extract --no-segment

    # Merge the extracted translations with the existing ones
    sh -c 'if [ -f translations/en/LC_MESSAGES/djangojs.po ]; then msgcat translations/en/LC_MESSAGES/django.po translations/en/LC_MESSAGES/djangojs.po -o translations/en/LC_MESSAGES/django.po; fi'
    rm -f translations/en/LC_MESSAGES/djangojs.po

    # Merge the updated source translation file with the existing translations for other languages
    msgmerge -U conf/locale/ar/LC_MESSAGES/django.po conf/locale/en/LC_MESSAGES/django.po
