[tox]
envlist = translation

[testenv:translation]
allowlist_externals =
    sh
    mv
    msgmerge
basepython = python3.11
changedir = {toxinidir}/video_xblock
deps =
    django<5.0
    edx-i18n-tools
commands =
    # Cleanup for any stale files that may be present in the source translation directory
    sh -c 'rm -f translations/en/LC_MESSAGES/django.po'
    sh -c 'rm -f translations/en/LC_MESSAGES/djangojs.po'

    # Prepare existing translations for the tool (they must be named django.po for the tool to recognize them)
    sh -c 'if [ -f translations/en/LC_MESSAGES/text.po ]; then cp translations/en/LC_MESSAGES/text.po translations/en/LC_MESSAGES/django.po; fi'

    # Extract source translation string using the i18n tool
    i18n_tool extract --no-segment

    # Merge the extracted translations with the existing ones
    sh -c 'if [ -f translations/en/LC_MESSAGES/djangojs.po ]; then msgcat translations/en/LC_MESSAGES/django.po translations/en/LC_MESSAGES/djangojs.po -o translations/en/LC_MESSAGES/django.po; fi'
    sh -c 'rm -f translations/en/LC_MESSAGES/text.po'
    mv translations/en/LC_MESSAGES/django.po translations/en/LC_MESSAGES/text.po
    sh -c 'rm -f translations/en/LC_MESSAGES/django.po'
    sh -c 'rm -f translations/en/LC_MESSAGES/djangojs.po'

    # Merge the updated source translation file with the existing translations for other languages
    msgmerge -U conf/locale/ar/LC_MESSAGES/text.po conf/locale/en/LC_MESSAGES/text.po
